# Spring Boot configuration
spring:
  # Thymeleaf configuration
  thymeleaf:
    cache: false
  # Security configuration
  security:
    user:
      name: paulo
      password: 123456
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tacocloud
    username: postgres
    password: root
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

# Server configuration
server:
  ssl:
    key-store: classpath:cert/springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
    enabled: true
  port: 8443

# Logging configuration
logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
    br:
      com:
        paulo:
          tacos: DEBUG
    root: INFO

  config: classpath:logback-spring.xml
  file:
    path: logs
    name: tacocloud.log

# Variables for the application

application:
  name: Taco Cloud

greeting:
  welcome: Welcome to ${application.name}!

taco:
  orders:
    pageSize: 10

